# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control_panel.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(568, 450)
        self.ON = QtWidgets.QPushButton(Form)
        self.ON.setGeometry(QtCore.QRect(30, 140, 93, 28))
        self.ON.setObjectName("ON")
        self.OFF = QtWidgets.QPushButton(Form)
        self.OFF.setGeometry(QtCore.QRect(130, 140, 93, 28))
        self.OFF.setObjectName("OFF")
        self._exit_ = QtWidgets.QPushButton(Form)
        self._exit_.setGeometry(QtCore.QRect(260, 400, 93, 28))
        self._exit_.setObjectName("_exit_")
        self.dial = QtWidgets.QDial(Form)
        self.dial.setGeometry(QtCore.QRect(390, 130, 50, 64))
        self.dial.setObjectName("dial")

        self.retranslateUi(Form)
        self._exit_.clicked.connect(Form.over) # type: ignore
        self.ON.clicked.connect(Form.turn_on) # type: ignore
        self.OFF.clicked.connect(Form.turn_off) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ON.setText(_translate("Form", "ON"))
        self.OFF.setText(_translate("Form", "OFF"))
        self._exit_.setText(_translate("Form", "退出"))
