# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'curtain.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(542, 466)
        self.curtain_1 = QtWidgets.QSlider(Form)
        self.curtain_1.setGeometry(QtCore.QRect(90, 50, 160, 22))
        self.curtain_1.setMaximum(100)
        self.curtain_1.setOrientation(QtCore.Qt.Horizontal)
        self.curtain_1.setObjectName("curtain_1")
        self.previous = QtWidgets.QPushButton(Form)
        self.previous.setGeometry(QtCore.QRect(180, 340, 75, 31))
        self.previous.setObjectName("previous")
        self.curtain_1_num = QtWidgets.QSpinBox(Form)
        self.curtain_1_num.setGeometry(QtCore.QRect(260, 40, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.curtain_1_num.setFont(font)
        self.curtain_1_num.setMaximum(100)
        self.curtain_1_num.setObjectName("curtain_1_num")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.previous.setText(_translate("Form", "返回"))
