# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DOOR.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.OPEN_FRONT = QtWidgets.QPushButton(Form)
        self.OPEN_FRONT.setGeometry(QtCore.QRect(150, 60, 75, 23))
        self.OPEN_FRONT.setObjectName("OPEN_FRONT")
        self.CLOSE_FRONT = QtWidgets.QPushButton(Form)
        self.CLOSE_FRONT.setGeometry(QtCore.QRect(230, 60, 75, 23))
        self.CLOSE_FRONT.setObjectName("CLOSE_FRONT")
        self.previous = QtWidgets.QPushButton(Form)
        self.previous.setGeometry(QtCore.QRect(130, 200, 93, 28))
        self.previous.setObjectName("previous")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 60, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(50, 130, 72, 15))
        self.label_2.setObjectName("label_2")
        self.CLOSE_BACK = QtWidgets.QPushButton(Form)
        self.CLOSE_BACK.setGeometry(QtCore.QRect(230, 130, 75, 23))
        self.CLOSE_BACK.setObjectName("CLOSE_BACK")
        self.OPEN_BACK = QtWidgets.QPushButton(Form)
        self.OPEN_BACK.setGeometry(QtCore.QRect(150, 130, 75, 23))
        self.OPEN_BACK.setObjectName("OPEN_BACK")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.OPEN_FRONT.setText(_translate("Form", "OPEN"))
        self.CLOSE_FRONT.setText(_translate("Form", "CLOSE"))
        self.previous.setText(_translate("Form", "返回"))
        self.label.setText(_translate("Form", "前门"))
        self.label_2.setText(_translate("Form", "后门"))
        self.CLOSE_BACK.setText(_translate("Form", "CLOSE"))
        self.OPEN_BACK.setText(_translate("Form", "OPEN"))
