# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DOOR.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.OPEN = QtWidgets.QPushButton(Form)
        self.OPEN.setGeometry(QtCore.QRect(60, 60, 75, 23))
        self.OPEN.setObjectName("OPEN")
        self.CLOSE = QtWidgets.QPushButton(Form)
        self.CLOSE.setGeometry(QtCore.QRect(230, 60, 75, 23))
        self.CLOSE.setObjectName("CLOSE")
        self.previous = QtWidgets.QPushButton(Form)
        self.previous.setGeometry(QtCore.QRect(130, 200, 93, 28))
        self.previous.setObjectName("previous")

        self.retranslateUi(Form)
        self.OPEN.clicked.connect(Form.turn_open)
        self.CLOSE.clicked.connect(Form.turn_close)
        self.previous.clicked.connect(Form.go_con_panel)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.OPEN.setText(_translate("Form", "OPEN"))
        self.CLOSE.setText(_translate("Form", "CLOSE"))
        self.previous.setText(_translate("Form", "返回"))
