# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LED.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.ON = QtWidgets.QPushButton(Form)
        self.ON.setGeometry(QtCore.QRect(30, 60, 93, 28))
        self.ON.setObjectName("ON")
        self.OFF = QtWidgets.QPushButton(Form)
        self.OFF.setGeometry(QtCore.QRect(170, 60, 93, 28))
        self.OFF.setObjectName("OFF")
        self.previous = QtWidgets.QPushButton(Form)
        self.previous.setGeometry(QtCore.QRect(100, 200, 93, 28))
        self.previous.setObjectName("previous")

        self.retranslateUi(Form)
        self.ON.clicked.connect(Form.turn_on) # type: ignore
        self.OFF.clicked.connect(Form.turn_off) # type: ignore
        self.previous.clicked.connect(Form.go_con_panel) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.ON.setText(_translate("Form", "ON"))
        self.OFF.setText(_translate("Form", "OFF"))
        self.previous.setText(_translate("Form", "返回"))
